### ISSUE TITLE
Whitelist not working

### ISSUE THREAD

**Issue by retep998** [SheepGoMeh/VisibilityPlugin#73]
I have a bunch of people on my whitelist, however when I hide all players in Visibility it also hides whitelisted players.

Also, while I'm at it, once whitelist works again, can I also request a way to still hide the pets/chocobos/minions of whitelisted players? Maybe like another column specifically for whitelisted players in the config?

**Comment by SheepGoMeh** [comment]
Fixed in 8ba8b90fffa614155ddd1368ea512fc2dd081165

**Comment by retep998** [comment]
I know this was closed as completed, but I'm using the latest non-testing version available (1.1.7.3) and whitelist is still not working. Players on the whitelist are still *not* visible.

**Comment by SheepGoMeh** [comment]
Thank you for pointing it out.
I did notice that there was a problem with the check, and it should work fine now.
If you do still encounter the problem, I would appreciate a follow-up with an issue!
